apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: echo
  namespace: sound-repeater
spec: 
  rules:
  - host: http://example.org
    https: 
      paths: 
      - path: /echo
        pathType: Prefix
        backend:
          service:
           name: echo-service
           port:
             number: 8080